export const FETCH_MY_TASKS_REQUEST = 'FETCH_MY_TASKS_REQUEST';
export const FETCH_MY_TASKS_SUCCESS = 'FETCH_MY_TASKS_SUCCESS';
export const FETCH_MY_TASKS_FAIL = 'FETCH_MY_TASKS_FAIL';

export const ADD_MY_TASK_REQUEST = 'ADD_MY_TASK_REQUEST';
export const ADD_MY_TASK_SUCCESS = 'ADD_MY_TASK_SUCCESS';
export const ADD_MY_TASK_FAIL = 'ADD_MY_TASK_FAIL';

export const UPDATE_MY_TASK_REQUEST = 'UPDATE_MY_TASK_REQUEST';
export const UPDATE_MY_TASK_SUCCESS = 'UPDATE_MY_TASK_SUCCESS';
export const UPDATE_MY_TASK_FAIL = 'UPDATE_MY_TASK_FAIL';

export const DELETE_MY_TASK_REQUEST = 'DELETE_MY_TASK_REQUEST';
export const DELETE_MY_TASK_SUCCESS = 'DELETE_MY_TASK_SUCCESS';
export const DELETE_MY_TASK_FAIL = 'DELETE_MY_TASK_FAIL';
